# Generated by Django 3.0.5 on 2020-06-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Pelicula')),
                ('director', models.CharField(max_length=100, verbose_name='Director')),
            ],
        ),
    ]
