# Generated by Django 3.0.5 on 2020-06-14 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_personaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musica', models.CharField(max_length=500, verbose_name='Música')),
                ('distribuidora', models.CharField(max_length=500, verbose_name='Distribuidora')),
                ('estreno', models.CharField(max_length=500, verbose_name='Estreno')),
                ('duracion', models.CharField(max_length=500, verbose_name='Duración')),
                ('presupuesto', models.CharField(max_length=500, verbose_name='Presupuesto')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peliculas.Peli')),
            ],
        ),
    ]
