# Generated by Django 3.0.5 on 2020-06-14 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planetas', models.CharField(max_length=500, verbose_name='Planetas')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peliculas.Peli')),
            ],
        ),
    ]
