# Generated by Django 3.0.5 on 2020-06-14 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_resumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peliculas.Peli')),
                ('personajes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peliculas.Personaje')),
                ('planetas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peliculas.Planeta')),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peliculas.Resumen')),
                ('tecnicos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peliculas.Tecnico')),
            ],
        ),
    ]
