# Generated by Django 3.0.5 on 2020-06-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('capitulos', models.CharField(max_length=500, verbose_name='Número de Capítulos')),
                ('emision', models.CharField(max_length=100, verbose_name='Años de Emisión')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
                ('distribuidora', models.CharField(max_length=200, verbose_name='Distribuidora')),
            ],
        ),
    ]
